In [2]:
import numpy as np 

In [14]:
np.random.seed(1)

In [15]:
a = np.random.normal(size=10)
a

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [16]:
a + 10

array([11.62434536,  9.38824359,  9.47182825,  8.92703138, 10.86540763,
        7.6984613 , 11.74481176,  9.2387931 , 10.3190391 ,  9.75062962])

In [17]:
a ** 3

array([  4.28583177,  -0.22894734,  -0.14734164,  -1.23526764,
         0.64813005, -12.19143546,   5.31184926,  -0.44107064,
         0.0324737 ,  -0.01550724])

In [18]:
a > 0

array([ True, False, False, False,  True, False,  True, False,  True,
       False])

In [19]:
a[3:6]

array([-1.07296862,  0.86540763, -2.3015387 ])

In [20]:
a[[3,4,5]]

array([-1.07296862,  0.86540763, -2.3015387 ])

In [21]:
a[[3,4,5]] * 20

array([-21.45937244,  17.30815259, -46.03077394])

In [22]:
a[[True, False, False, False, False, False, False, False, False, False]]

array([1.62434536])

In [29]:
a[a < 0]

array([-0.61175641, -0.52817175, -1.07296862, -2.3015387 , -0.7612069 ,
       -0.24937038])

In [30]:
a[a > 0]

array([1.62434536, 0.86540763, 1.74481176, 0.3190391 ])

In [34]:
a[(a > -0.5) & (a < 0.5)] 

array([ 0.3190391 , -0.24937038])